-- Create locations table for Cameroon towns and quarters
CREATE TABLE public.locations (
    id SERIAL PRIMARY KEY,
    region TEXT NOT NULL,
    department TEXT,
    town TEXT NOT NULL,
    quarter TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX idx_locations_region ON locations(region);
CREATE INDEX idx_locations_town ON locations(town);
CREATE INDEX idx_locations_quarter ON locations(quarter);
CREATE INDEX idx_locations_search ON locations USING gin(to_tsvector('english', region || ' ' || town || ' ' || COALESCE(quarter, '')));

-- Enable RLS
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;

-- Allow public read access to locations
CREATE POLICY "Locations are viewable by everyone" ON locations
    FOR SELECT USING (true);

-- Insert comprehensive Cameroon locations data
INSERT INTO locations (region, department, town, quarter) VALUES
-- Adamawa Region
('Adamawa', 'Djérem', 'Tibati', NULL),
('Adamawa', 'Djérem', 'Tibati', 'Centre-ville'),
('Adamawa', 'Djérem', 'Tibati', 'Nassarawa'),
('Adamawa', 'Faro-et-Déo', 'Tignère', NULL),
('Adamawa', 'Faro-et-Déo', 'Tignère', 'Centre'),
('Adamawa', 'Faro-et-Déo', 'Kontcha', NULL),
('Adamawa', 'Mayo-Banyo', 'Banyo', NULL),
('Adamawa', 'Mayo-Banyo', 'Banyo', 'Centre-ville'),
('Adamawa', 'Mbéré', 'Meiganga', NULL),
('Adamawa', 'Mbéré', 'Meiganga', 'Centre'),
('Adamawa', 'Vina', 'Ngaoundéré', NULL),
('Adamawa', 'Vina', 'Ngaoundéré', 'Centre-ville'),
('Adamawa', 'Vina', 'Ngaoundéré', 'Dang'),
('Adamawa', 'Vina', 'Ngaoundéré', 'Haoussa'),
('Adamawa', 'Vina', 'Ngaoundéré', 'Mabanga'),
('Adamawa', 'Vina', 'Ngaoundéré', 'Sabongari'),

-- Centre Region
('Centre', 'Haute-Sanaga', 'Nanga-Eboko', NULL),
('Centre', 'Lékié', 'Monatélé', NULL),
('Centre', 'Lékié', 'Obala', NULL),
('Centre', 'Lékié', 'Evodoula', NULL),
('Centre', 'Mbam-et-Inoubou', 'Bafia', NULL),
('Centre', 'Mbam-et-Inoubou', 'Bafia', 'Centre'),
('Centre', 'Mbam-et-Kim', 'Ntui', NULL),
('Centre', 'Mefou-et-Afamba', 'Edzendouan', NULL),
('Centre', 'Mefou-et-Akono', 'Akono', NULL),
('Centre', 'Mefou-et-Akono', 'Bikok', NULL),
('Centre', 'Mfoundi', 'Yaoundé', NULL),
('Centre', 'Mfoundi', 'Yaoundé', 'Bastos'),
('Centre', 'Mfoundi', 'Yaoundé', 'Bonanjo'),
('Centre', 'Mfoundi', 'Yaoundé', 'Centre-ville'),
('Centre', 'Mfoundi', 'Yaoundé', 'Essos'),
('Centre', 'Mfoundi', 'Yaoundé', 'Mvog-Mbi'),
('Centre', 'Mfoundi', 'Yaoundé', 'Nlongkak'),
('Centre', 'Mfoundi', 'Yaoundé', 'Nkoldongo'),
('Centre', 'Mfoundi', 'Yaoundé', 'Emana'),
('Centre', 'Mfoundi', 'Yaoundé', 'Kondengui'),
('Centre', 'Mfoundi', 'Yaoundé', 'Djoungolo'),
('Centre', 'Mfoundi', 'Yaoundé', 'Efoulan'),
('Centre', 'Mfoundi', 'Yaoundé', 'Ekounou'),
('Centre', 'Mfoundi', 'Yaoundé', 'Madagascar'),
('Centre', 'Mfoundi', 'Yaoundé', 'Mokolo'),
('Centre', 'Mfoundi', 'Yaoundé', 'Nkomo'),
('Centre', 'Mfoundi', 'Yaoundé', 'Olembe'),
('Centre', 'Mfoundi', 'Yaoundé', 'Omnisport'),
('Centre', 'Mfoundi', 'Yaoundé', 'Simbock'),
('Centre', 'Mfoundi', 'Yaoundé', 'Tsinga'),
('Centre', 'Nyong-et-Kéllé', 'Eséka', NULL),
('Centre', 'Nyong-et-Mfoumou', 'Akonolinga', NULL),
('Centre', 'Nyong-et-Soo', 'Mbalmayo', NULL),

-- East Region
('East', 'Boumba-et-Ngoko', 'Yokadouma', NULL),
('East', 'Haut-Nyong', 'Abong-Mbang', NULL),
('East', 'Haut-Nyong', 'Doumé', NULL),
('East', 'Haut-Nyong', 'Lomié', NULL),
('East', 'Haut-Nyong', 'Messok', NULL),
('East', 'Kadey', 'Batouri', NULL),
('East', 'Kadey', 'Ndelele', NULL),
('East', 'Lom-et-Djérem', 'Bétaré-Oya', NULL),
('East', 'Lom-et-Djérem', 'Garoua-Boulaï', NULL),

-- Far North Region
('Far North', 'Diamaré', 'Maroua', NULL),
('Far North', 'Diamaré', 'Maroua', 'Centre-ville'),
('Far North', 'Diamaré', 'Maroua', 'Domayo'),
('Far North', 'Diamaré', 'Maroua', 'Doualaré'),
('Far North', 'Diamaré', 'Maroua', 'Dougoy'),
('Far North', 'Diamaré', 'Maroua', 'Founangué'),
('Far North', 'Diamaré', 'Maroua', 'Hardé'),
('Far North', 'Diamaré', 'Maroua', 'Kongola'),
('Far North', 'Diamaré', 'Bogo', NULL),
('Far North', 'Logone-et-Chari', 'Kousséri', NULL),
('Far North', 'Logone-et-Chari', 'Blangoua', NULL),
('Far North', 'Mayo-Danay', 'Yagoua', NULL),
('Far North', 'Mayo-Kani', 'Kaélé', NULL),
('Far North', 'Mayo-Sava', 'Mora', NULL),
('Far North', 'Mayo-Tsanaga', 'Mokolo', NULL),

-- Littoral Region  
('Littoral', 'Moungo', 'Nkongsamba', NULL),
('Littoral', 'Moungo', 'Nkongsamba', 'Centre'),
('Littoral', 'Moungo', 'Loum', NULL),
('Littoral', 'Nkam', 'Yabassi', NULL),
('Littoral', 'Sanaga-Maritime', 'Edéa', NULL),
('Littoral', 'Wouri', 'Douala', NULL),
('Littoral', 'Wouri', 'Douala', 'Akwa'),
('Littoral', 'Wouri', 'Douala', 'Bali'),
('Littoral', 'Wouri', 'Douala', 'Bassa'),
('Littoral', 'Wouri', 'Douala', 'Bell'),
('Littoral', 'Wouri', 'Douala', 'Bonapriso'),
('Littoral', 'Wouri', 'Douala', 'Bonanjo'),
('Littoral', 'Wouri', 'Douala', 'Bépanda'),
('Littoral', 'Wouri', 'Douala', 'Bessengue'),
('Littoral', 'Wouri', 'Douala', 'Deido'),
('Littoral', 'Wouri', 'Douala', 'Kotto'),
('Littoral', 'Wouri', 'Douala', 'Logbaba'),
('Littoral', 'Wouri', 'Douala', 'Makepe'),
('Littoral', 'Wouri', 'Douala', 'New Bell'),
('Littoral', 'Wouri', 'Douala', 'Nylon'),
('Littoral', 'Wouri', 'Douala', 'PK 8'),
('Littoral', 'Wouri', 'Douala', 'PK 11'),
('Littoral', 'Wouri', 'Douala', 'PK 14'),
('Littoral', 'Wouri', 'Douala', 'Village'),
('Littoral', 'Wouri', 'Douala', 'Yassa'),

-- North Region
('North', 'Bénoué', 'Garoua', NULL),
('North', 'Bénoué', 'Garoua', 'Centre-ville'),
('North', 'Bénoué', 'Garoua', 'Doualaré'),
('North', 'Bénoué', 'Garoua', 'Kollangui'),
('North', 'Bénoué', 'Garoua', 'Roumde Adjia'),
('North', 'Bénoué', 'Garoua', 'Tchéboa'),
('North', 'Bénoué', 'Lagdo', NULL),
('North', 'Faro', 'Poli', NULL),
('North', 'Mayo-Louti', 'Guider', NULL),
('North', 'Mayo-Rey', 'Tcholliré', NULL),
('North', 'Mayo-Rey', 'Rey-Bouba', NULL),

-- Northwest Region
('Northwest', 'Boyo', 'Fundong', NULL),
('Northwest', 'Bui', 'Kumbo', NULL),
('Northwest', 'Donga-Mantung', 'Nkambe', NULL),
('Northwest', 'Menchum', 'Wum', NULL),
('Northwest', 'Mezam', 'Bamenda', NULL),
('Northwest', 'Mezam', 'Bamenda', 'Commercial Avenue'),
('Northwest', 'Mezam', 'Bamenda', 'Government Station'),
('Northwest', 'Mezam', 'Bamenda', 'Mankon'),
('Northwest', 'Mezam', 'Bamenda', 'Mbatu'),
('Northwest', 'Mezam', 'Bamenda', 'Nkwen'),
('Northwest', 'Mezam', 'Bamenda', 'Old Town'),
('Northwest', 'Mezam', 'Bamenda', 'Up Station'),
('Northwest', 'Momo', 'Mbengwi', NULL),
('Northwest', 'Ngo-Ketunjia', 'Ndop', NULL),

-- South Region
('South', 'Dja-et-Lobo', 'Sangmélima', NULL),
('South', 'Mvila', 'Ebolowa', NULL),
('South', 'Mvila', 'Ebolowa', 'Centre'),
('South', 'Mvila', 'Mengong', NULL),
('South', 'Océan', 'Kribi', NULL),
('South', 'Océan', 'Campo', NULL),
('South', 'Vallée-du-Ntem', 'Ambam', NULL),
('South', 'Vallée-du-Ntem', 'Olamze', NULL),

-- Southwest Region
('Southwest', 'Fako', 'Limbe', NULL),
('Southwest', 'Fako', 'Limbe', 'Batoke'),
('Southwest', 'Fako', 'Limbe', 'Church Street'),
('Southwest', 'Fako', 'Limbe', 'Half Mile'),
('Southwest', 'Fako', 'Limbe', 'Motowo'),
('Southwest', 'Fako', 'Buea', NULL),
('Southwest', 'Fako', 'Buea', 'Bonduma'),
('Southwest', 'Fako', 'Buea', 'Great Soppo'),
('Southwest', 'Fako', 'Buea', 'Molyko'),
('Southwest', 'Fako', 'Buea', 'Muea'),
('Southwest', 'Fako', 'Buea', 'Town'),
('Southwest', 'Fako', 'Tiko', NULL),
('Southwest', 'Koupé-Manengouba', 'Bangem', NULL),
('Southwest', 'Lebialem', 'Menji', NULL),
('Southwest', 'Manyu', 'Mamfe', NULL),
('Southwest', 'Meme', 'Kumba', NULL),
('Southwest', 'Meme', 'Kumba', 'Fiango'),
('Southwest', 'Meme', 'Kumba', 'Mbeng'),
('Southwest', 'Meme', 'Kumba', 'Mile 4'),
('Southwest', 'Meme', 'Kumba', 'Town'),
('Southwest', 'Ndian', 'Mundemba', NULL),

-- West Region
('West', 'Bamboutos', 'Mbouda', NULL),
('West', 'Hauts-Plateaux', 'Baham', NULL),
('West', 'Haut-Nkam', 'Bafang', NULL),
('West', 'Koung-Khi', 'Bandjoun', NULL),
('West', 'Ménoua', 'Dschang', NULL),
('West', 'Ménoua', 'Dschang', 'Centre-ville'),
('West', 'Ménoua', 'Dschang', 'Fongo-Tongo'),
('West', 'Ménoua', 'Dschang', 'Foto'),
('West', 'Ménoua', 'Fokoué', NULL),
('West', 'Mifi', 'Bafoussam', NULL),
('West', 'Mifi', 'Bafoussam', 'Centre-ville'),
('West', 'Mifi', 'Bafoussam', 'Djeleng'),
('West', 'Mifi', 'Bafoussam', 'Famla'),
('West', 'Mifi', 'Bafoussam', 'Tamdja'),
('West', 'Mifi', 'Bafoussam', 'Tougang'),
('West', 'Noun', 'Foumban', NULL),
('West', 'Noun', 'Foumban', 'Centre'),
('West', 'Noun', 'Koutaba', NULL),
('West', 'Ndé', 'Bangangté', NULL);
